export * from './client.js';
export * from './auth.js';
export * from './adminAuth.js';
export * from './idCard.js';
export * from './media.js';
export * from './verifiedStudents.js';
export * from './otpService.js';
export * from './emailService.js';
export * from './smsService.js';
export * from './storageService.js';
export * from './resources.js';
export * from './notices.js';
export * from './courses.js';
export * from './results.js';
export * from './directoryService.js';
export * from './notificationService.js';
export * from './executivesService.js';
export * from './newsService.js';
export * from './administrationService.js';
export * from './galleryService.js';
export * from './spiritualLifeService.js';
export * from './eventsService.js';
export * from './electraService.js';
export * from './payments.js';
export { default } from './client.js';

